// Generated by Wrangler by running `wrangler types`

interface Env {
	MULTI_TENANT: "false";
	CONFIG_DO: DurableObjectNamespace<import("./src/index").ConfigDO>;
	WATCHER_DO: DurableObjectNamespace<import("./src/index").WatcherDO>;
}
declare module "*.sql" {
	const value: string;
	export default value;
}