// Generated by Wrangler by running `wrangler types`

interface Env {
	MULTI_TENANT: "false";
	CONFIG_DO: DurableObjectNamespace /* ConfigDO */;
	WATCHER_DO: DurableObjectNamespace /* WatcherDO */;
}
